env:
 global:
   - secure: "3o4PfOZnI4U1X45lKcjwdx7np+tEJ5uk2t7P+4Ja5JLShSPmcl66WbFFr4AKcJcpJNj98jmu9q9CPcTsIYfotdmWc+d/gamlCHyuKeRUmpqbe5fMxeWP56HdCnOI8xVHLhclTIXWdY7pLJIUbMxyQ0vNhx9zNVBgzQjz8cUvEsGE4QbZCE5VSUBDb6kgLhY1dYBMn04XSJXc0Mui/pdzMWLpd8Tun3FiE5l/P4GRiC/oVuNqmOQujvud/gv03RYTQ7AdLDuMJBuygjTw2xjjvvU64akoO4qCOaWZdc5WwR+EEOQqAsrtkMbqCl8Q9/pOPceuRV+Z5Aj8umODMYNJVnUbrFev4XiI69tnzK01j+NuJAozUu5RMArMg29aZE+f87dQkNqgagtz3MT/MvUdcIxw7ccwjkq71rUqrp9i/Zfxb72/WExDg/i+Td5Xi2OZ+AzPZQIp9K2kt9S4AfIEDkpn+VrLMg1Pa7h0BJ8+PaIK/nfPhOt+0C6y4F0sXjy25LVXuNtrO7prqOmk5I+DDvcnlM2RUpq1fNNyMnFdCXkhXDTf5eH+SGWbLlBXSnyPd1Ww3l3HP2TAOWzd4q4CnzDXhnbiw1HE3LtNrz7zm9x0rvoNUUk/fqjdBlh4R641u87S51GXucsZWRCbg9LJs4LAlgkfMIpke62uadakvGA="

language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g  #生成

after_script:
  - rm -rf .deploy_git
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址        - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git   
  - git remote -v             
  - cp -Rf ../public/* ../.deploy_git
  - git status 
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称

branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/ZadaWu/ZadaWu.github.io.git  #设置GH_REF，注意更改yourname

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - 1137152932@qq.com
    - zada.wu@gmail.com
  on_success: change
  on_failure: always
